### ISSUE TITLE
Is this image will be fixed on freebsd9?

### ISSUE THREAD

**Issue by ebraminio** [sandvine/freebsd-cross-build#1]
Thanks for this work, we are using the image for https://github.com/behdad/harfbuzz/pull/595 for testing compile of the project with freebsd9 and gcc4. My question is, is the image supposed to be fixed on the version or we should use a permanent version to ensure it will not be changed over the time? If it supposed to be changed, it would be nice if some tags would be added. Thanks.

**Comment by donbowman** [comment]
I guess the build script could be modified to fetch each set of iso, and then build containers for each w/ tags.

**Comment by ebraminio** [comment]
Oh great, if so, I like to suggest the particular version of the uploaded image on dockerhub https://hub.docker.com/r/donbowman/freebsd-cross-build/tags/ to be tagged with the freebsd version. Thanks.

**Comment by ebraminio** [comment]
Closing this as it is not related to the repo directly, thank you :)
